MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.11                  # [osx]
macos_min_version:         # [osx]
  - 10.11                  # [osx]
# CONDA_BUILD_SYSROOT:       # [osx and x86_64]
#   - /opt/MacOSX10.11.sdk   # [osx and x86_64]
