MACOSX_SDK_VERSION:             # [osx and (x86_64 or arm64)]
  - 12.3               # [(osx and arm64)]
  - 10.14                       # [osx and x86_64]
CONDA_BUILD_SYSROOT:            # [osx and (x86_64 or arm64)]
  - /opt/MacOSX10.14.sdk        # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk  # [(osx and arm64)]
macos_min_version:              # [osx and x86_64]
  - 10.12                       # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:       # [osx and x86_64]
  - 10.12                       # [osx and x86_64]
