# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.2.3" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 8ad8e3521172922c2a3ac897ac2bee0349ef75286909a60150cfa4e774596827
  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt the default backend.
    - cfg_qt5agg.patch  # [not osx]
    # Removes framework check from osx backend (seems unneeded)
    - osx-frame.patch  # [osx]

build:
  number: 0

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - backports.functools_lru_cache  # [py2k]
    - numpy
    - python-dateutil
    - freetype
    - msinttypes  # [win]
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
    #- py2cairo  # [linux and py2k]
    - libpng
    - zlib         # [win]
    - pyqt        # [not osx]
    - tk        # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu       # [linux]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - backports.functools_lru_cache  # [py2k]
    - cycler >=0.10
    - python-dateutil
    - freetype
    - pytz
    - pyparsing
    #- py2cairo  # [linux and py2k]
    - libpng
    - pyqt        # [not osx]
    - tk        # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu       # [linux]
    - tornado
    - kiwisolver

test:
  imports:
    - matplotlib
    - matplotlib.pyplot
    - matplotlib._image
    - matplotlib._path
    - matplotlib._png
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.ft2font
    - matplotlib.ttconv
    - matplotlib.backends._tkagg  # [not win]
    - mpl_toolkits
    - pylab

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
