# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "1.5.3" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: c72276afc11f0b77cee736a783861039c0284d2e4739de8ca09d2dd1407745aa
  patches:
    # Find Tcl and libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]
    # Removes framework check from osx backend (seems unneeded)
    - osx-frame.patch  # [osx]

build:
    number: 8

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.7|2.7.*
    - msinttypes  # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
#    - py2cairo  # [linux and py2k]
    - tornado
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*  # [win]
    - pyqt 4.11.*  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 58.*  # [linux]
  run:
    - python
    - setuptools
    - numpy x.x
    - cycler
    - python-dateutil
    - freetype 2.7|2.7.*
    - pytz
    - pyparsing
#    - py2cairo  # [linux and py2k]
    - libpng >=1.6.28,<1.7
    - pyqt 4.11.*  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 58.*  # [linux]
    - tornado

test:
  imports:
    - matplotlib
    - matplotlib.pyplot
    - matplotlib._cntr
    - matplotlib._delaunay
    - matplotlib._image
    - matplotlib._path
    - matplotlib._png
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.ft2font
    - matplotlib.ttconv
    - matplotlib.backends._tkagg  # [not win]
    - mpl_toolkits
    - pylab

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
